import React, { useState, useEffect } from "react";
import "./QueryComponent.css";


const fields2001 = [
  { id: "No_HH", label: "Number of Households" },
  { id: "TOT_P", label: "Total Population" },
  { id: "TOT_M", label: "Total Males" },
  { id: "TOT_F", label: "Total Females" },
  { id: "P_06", label: "Population Age 0-6" },
  { id: "M_06", label: "Male Population Age 0-6" },
  { id: "F_06", label: "Female Population Age 0-6" },
  { id: "P_SC", label: "Scheduled Caste Population" },
  { id: "M_SC", label: "Male Scheduled Caste Population" },
  { id: "F_SC", label: "Female Scheduled Caste Population" },
  { id: "P_ST", label: "Scheduled Tribe Population" },
  { id: "M_ST", label: "Male Scheduled Tribe Population" },
  { id: "F_ST", label: "Female Scheduled Tribe Population" },
  { id: "P_LIT", label: "Literate Population" },
  { id: "M_LIT", label: "Male Literate Population" },
  { id: "F_LIT", label: "Female Literate Population" },
  { id: "P_ILL", label: "Illiterate Population" },
  { id: "M_ILL", label: "Male Illiterate Population" },
  { id: "F_ILL", label: "Female Illiterate Population" },
  { id: "TOT_WORK_P", label: "Total Working Population" },
  { id: "TOT_WORK_M", label: "Total Working Males" },
  { id: "TOT_WORK_F", label: "Total Working Females" },
  { id: "MAINWORK_P", label: "Main Workers Population" },
  { id: "MAINWORK_M", label: "Main Workers Males" },
  { id: "MAINWORK_F", label: "Main Workers Females" },
  { id: "MAIN_CL_P", label: "Main Cultivators Population" },
  { id: "MAIN_CL_M", label: "Main Cultivators Males" },
  { id: "MAIN_CL_F", label: "Main Cultivators Females" },
  { id: "MAIN_AL_P", label: "Main Agricultural Laborers Population" },
  { id: "MAIN_AL_M", label: "Main Agricultural Laborers Males" },
  { id: "MAIN_AL_F", label: "Main Agricultural Laborers Females" },
  { id: "MAIN_HH_P", label: "Main Household Industry Workers Population" },
  { id: "MAIN_HH_M", label: "Main Household Industry Workers Males" },
  { id: "MAIN_HH_F", label: "Main Household Industry Workers Females" },
  { id: "MAIN_OT_P", label: "Main Other Workers Population" },
  { id: "MAIN_OT_M", label: "Main Other Workers Males" },
  { id: "MAIN_OT_F", label: "Main Other Workers Females" },
  { id: "MARGWORK_P", label: "Marginal Workers Population" },
  { id: "MARGWORK_M", label: "Marginal Workers Males" },
  { id: "MARGWORK_F", label: "Marginal Workers Females" },
  { id: "MARG_CL_P", label: "Marginal Cultivators Population" },
  { id: "MARG_CL_M", label: "Marginal Cultivators Males" },
  { id: "MARG_CL_F", label: "Marginal Cultivators Females" },
  { id: "MARG_AL_P", label: "Marginal Agricultural Laborers Population" },
  { id: "MARG_AL_M", label: "Marginal Agricultural Laborers Males" },
  { id: "MARG_AL_F", label: "Marginal Agricultural Laborers Females" },
  { id: "MARG_HH_P", label: "Marginal Household Industry Workers Population" },
  { id: "MARG_HH_M", label: "Marginal Household Industry Workers Males" },
  { id: "MARG_HH_F", label: "Marginal Household Industry Workers Females" },
  { id: "MARG_OT_P", label: "Marginal Other Workers Population" },
  { id: "MARG_OT_M", label: "Marginal Other Workers Males" },
  { id: "MARG_OT_F", label: "Marginal Other Workers Females" },
  { id: "NON_WORK_P", label: "Non-Working Population" },
  { id: "NON_WORK_M", label: "Non-Working Males" },
  { id: "NON_WORK_F", label: "Non-Working Females" },
];

const fields2011 = [
  { id: "No_HH", label: "Number of Households" },
  { id: "TOT_P", label: "Total Population" },
  { id: "TOT_M", label: "Total Males" },
  { id: "TOT_F", label: "Total Females" },
  { id: "P_06", label: "Population Age 0-6" },
  { id: "M_06", label: "Male Population Age 0-6" },
  { id: "F_06", label: "Female Population Age 0-6" },
  { id: "P_SC", label: "Scheduled Caste Population" },
  { id: "M_SC", label: "Male Scheduled Caste Population" },
  { id: "F_SC", label: "Female Scheduled Caste Population" },
  { id: "P_ST", label: "Scheduled Tribe Population" },
  { id: "M_ST", label: "Male Scheduled Tribe Population" },
  { id: "F_ST", label: "Female Scheduled Tribe Population" },
  { id: "P_LIT", label: "Literate Population" },
  { id: "M_LIT", label: "Male Literate Population" },
  { id: "F_LIT", label: "Female Literate Population" },
  { id: "P_ILL", label: "Illiterate Population" },
  { id: "M_ILL", label: "Male Illiterate Population" },
  { id: "F_ILL", label: "Female Illiterate Population" },
  { id: "TOT_WORK_P", label: "Total Working Population" },
  { id: "TOT_WORK_M", label: "Total Working Males" },
  { id: "TOT_WORK_F", label: "Total Working Females" },
  { id: "MAINWORK_P", label: "Main Workers Population" },
  { id: "MAINWORK_M", label: "Main Workers Males" },
  { id: "MAINWORK_F", label: "Main Workers Females" },
  { id: "MAIN_CL_P", label: "Main Cultivators Population" },
  { id: "MAIN_CL_M", label: "Main Cultivators Males" },
  { id: "MAIN_CL_F", label: "Main Cultivators Females" },
  { id: "MAIN_AL_P", label: "Main Agricultural Laborers Population" },
  { id: "MAIN_AL_M", label: "Main Agricultural Laborers Males" },
  { id: "MAIN_AL_F", label: "Main Agricultural Laborers Females" },
  { id: "MAIN_HH_P", label: "Main Household Industry Workers Population" },
  { id: "MAIN_HH_M", label: "Main Household Industry Workers Males" },
  { id: "MAIN_HH_F", label: "Main Household Industry Workers Females" },
  { id: "MAIN_OT_P", label: "Main Other Workers Population" },
  { id: "MAIN_OT_M", label: "Main Other Workers Males" },
  { id: "MAIN_OT_F", label: "Main Other Workers Females" },
  { id: "MARGWORK_P", label: "Marginal Workers Population" },
  { id: "MARGWORK_M", label: "Marginal Workers Males" },
  { id: "MARGWORK_F", label: "Marginal Workers Females" },
  { id: "MARG_CL_P", label: "Marginal Cultivators Population" },
  { id: "MARG_CL_M", label: "Marginal Cultivators Males" },
  { id: "MARG_CL_F", label: "Marginal Cultivators Females" },
  { id: "MARG_AL_P", label: "Marginal Agricultural Laborers Population" },
  { id: "MARG_AL_M", label: "Marginal Agricultural Laborers Males" },
  { id: "MARG_AL_F", label: "Marginal Agricultural Laborers Females" },
  { id: "MARG_HH_P", label: "Marginal Household Industry Workers Population" },
  { id: "MARG_HH_M", label: "Marginal Household Industry Workers Males" },
  { id: "MARG_HH_F", label: "Marginal Household Industry Workers Females" },
  { id: "MARG_OT_P", label: "Marginal Other Workers Population" },
  { id: "MARG_OT_M", label: "Marginal Other Workers Males" },
  { id: "MARG_OT_F", label: "Marginal Other Workers Females" },
  { id: "MARGWORK_3_6_P", label: "Marginal Workers 3-6 Months Population" },
  { id: "MARGWORK_3_6_M", label: "Marginal Workers 3-6 Months Males" },
  { id: "MARGWORK_3_6_F", label: "Marginal Workers 3-6 Months Females" },
  { id: "MARG_CL_3_6_P", label: "Marginal Cultivators 3-6 Months Population" },
  { id: "MARG_CL_3_6_M", label: "Marginal Cultivators 3-6 Months Males" },
  { id: "MARG_CL_3_6_F", label: "Marginal Cultivators 3-6 Months Females" },
  {
    id: "MARG_AL_3_6_P",
    label: "Marginal Agricultural Laborers 3-6 Months Population",
  },
  {
    id: "MARG_AL_3_6_M",
    label: "Marginal Agricultural Laborers 3-6 Months Males",
  },
  {
    id: "MARG_AL_3_6_F",
    label: "Marginal Agricultural Laborers 3-6 Months Females",
  },
  {
    id: "MARG_HH_3_6_P",
    label: "Marginal Household Industry Workers 3-6 Months Population",
  },
  {
    id: "MARG_HH_3_6_M",
    label: "Marginal Household Industry Workers 3-6 Months Males",
  },
  {
    id: "MARG_HH_3_6_F",
    label: "Marginal Household Industry Workers 3-6 Months Females",
  },
  {
    id: "MARG_OT_3_6_P",
    label: "Marginal Other Workers 3-6 Months Population",
  },
  { id: "MARG_OT_3_6_M", label: "Marginal Other Workers 3-6 Months Males" },
  { id: "MARG_OT_3_6_F", label: "Marginal Other Workers 3-6 Months Females" },
  { id: "MARGWORK_0_3_P", label: "Marginal Workers 0-3 Months Population" },
  { id: "MARGWORK_0_3_M", label: "Marginal Workers 0-3 Months Males" },
  { id: "MARGWORK_0_3_F", label: "Marginal Workers 0-3 Months Females" },
  { id: "MARG_CL_0_3_P", label: "Marginal Cultivators 0-3 Months Population" },
  { id: "MARG_CL_0_3_M", label: "Marginal Cultivators 0-3 Months Males" },
  { id: "MARG_CL_0_3_F", label: "Marginal Cultivators 0-3 Months Females" },
  {
    id: "MARG_AL_0_3_P",
    label: "Marginal Agricultural Laborers 0-3 Months Population",
  },
  {
    id: "MARG_AL_0_3_M",
    label: "Marginal Agricultural Laborers 0-3 Months Males",
  },
  {
    id: "MARG_AL_0_3_F",
    label: "Marginal Agricultural Laborers 0-3 Months Females",
  },
  {
    id: "MARG_HH_0_3_P",
    label: "Marginal Household Industry Workers 0-3 Months Population",
  },
  {
    id: "MARG_HH_0_3_M",
    label: "Marginal Household Industry Workers 0-3 Months Males",
  },
  {
    id: "MARG_HH_0_3_F",
    label: "Marginal Household Industry Workers 0-3 Months Females",
  },
  {
    id: "MARG_OT_0_3_P",
    label: "Marginal Other Workers 0-3 Months Population",
  },
  { id: "MARG_OT_0_3_M", label: "Marginal Other Workers 0-3 Months Males" },
  { id: "MARG_OT_0_3_F", label: "Marginal Other Workers 0-3 Months Females" },
  { id: "NON_WORK_P", label: "Non-Working Population" },
  { id: "NON_WORK_M", label: "Non-Working Males" },
  { id: "NON_WORK_F", label: "Non-Working Females" },
];

const total_1991 = [
  
  { id: "T_POPULAT°,N,12,0", label: "Total Population" },
  { id: "DENSITY,N,10,0", label: "Density" },
  { id: "HOUSEHOLDS,N,14,0", label: "Households" },
  { id: "PERS/HOUSE,N,13,1", label: "Persons per Household" },
  { id: "MALE_POP,N,12,0", label: "Male Population" },
  { id: "FEMALE_POP,N,13,0", label: "Female Population" },
  { id: "SR_POPULAT,N,13,0", label: "Sex Ratio" },
  { id: "T_CHILDREN,N,12,0", label: "Total Children" },
  { id: "M_CHILDREN,N,12,0", label: "Male Children" },
  { id: "F_CHILDREN,N,12,0", label: "Female Children" },
  { id: "SR_CHILDRE,N,12,0", label: "Sex Ratio Children" },
  { id: "T_SC,N,8,0", label: "Total SC" },
  { id: "T%_SC,N,8,2", label: "Percentage SC" },
  { id: "M_SC,N,7,0", label: "Male SC" },
  { id: "F_SC,N,7,0", label: "Female SC" },
  { id: "SR_SC,N,8,0", label: "Sex Ratio SC" },
  { id: "T_ST,N,7,0", label: "Total ST" },
  { id: "T%_ST,N,8,2", label: "Percentage ST" },
  { id: "M_ST,N,7,0", label: "Male ST" },
  { id: "F_ST,N,6,0", label: "Female ST" },
  { id: "SR_ST,N,8,0", label: "Sex Ratio ST" },
  { id: "T_LITTERAT,N,11,0", label: "Total Literate" },
  { id: "T%_LITTERA,N,12,2", label: "Percentage Literate" },
  { id: "M_LITTERAT,N,12,0", label: "Male Literate" },
  { id: "F_LITTERAT,N,11,0", label: "Female Literate" },
  { id: "SR_LITTERA,N,12,0", label: "Sex Ratio Literate" },
  { id: "T_WORKERS,N,13,0", label: "Total Workers" },
  { id: "T%_WORKERS,N,14,2", label: "Percentage Workers" },
  { id: "M_WORKERS,N,14,0", label: "Male Workers" },
  { id: "F_WORKERS,N,14,0", label: "Female Workers" },
  { id: "SR_WORKERS,N,14,0", label: "Sex Ratio Workers" },
  { id: "T_MARGINAL,N,12,0", label: "Total Marginal Workers" },
  { id: "T%_MARGINA,N,13,2", label: "Percentage Marginal Workers" },
  { id: "M_MARGINAL,N,13,0", label: "Male Marginal Workers" },
  { id: "F_MARGINAL,N,12,0", label: "Female Marginal Workers" },
  { id: "SR_MARGINA,N,13,0", label: "Sex Ratio Marginal Workers" },
  { id: "T_NONWORK,N,14,0", label: "Total Non-Workers" },
  { id: "T%_NONWORK,N,14,2", label: "Percentage Non-Workers" },
  { id: "M_NONWORK,N,14,0", label: "Male Non-Workers" },
  { id: "F_NONWORK,N,14,0", label: "Female Non-Workers" },
  { id: "SR_NONWORK,N,14,0", label: "Sex Ratio Non-Workers" },
  { id: "T_PRIMARY,N,12,0", label: "Total Primary Workers" },
  { id: "T%_PRIMARY,N,13,2", label: "Percentage Primary Workers" },
  { id: "M_PRIMARY,N,13,0", label: "Male Primary Workers" },
  { id: "F_PRIMARY,N,12,0", label: "Female Primary Workers" },
  { id: "SR_PRIMARY,N,13,0", label: "Sex Ratio Primary Workers" },
  { id: "T_SECUND,N,11,0", label: "Total Secondary Workers" },
  { id: "T%_SECUND,N,13,2", label: "Percentage Secondary Workers" },
  { id: "M_SECUND,N,12,0", label: "Male Secondary Workers" },
  { id: "F_SECUND,N,12,0", label: "Female Secondary Workers" },
  { id: "SR_SECUND,N,13,0", label: "Sex Ratio Secondary Workers" },
  { id: "T_TERTIARY,N,12,0", label: "Total Tertiary Workers" },
  { id: "T%_TERTIAR,N,12,2", label: "Percentage Tertiary Workers" },
  { id: "M_TERTIARY,N,12,0", label: "Male Tertiary Workers" },
  { id: "F_TERTIARY,N,12,0", label: "Female Tertiary Workers" },
  { id: "SR_TERTIAR,N,12,0", label: "Sex Ratio Tertiary Workers" },
  { id: "T_CULTIVAT,N,11,0", label: "Total Cultivators" },
  { id: "T%_CULTIVA,N,12,2", label: "Percentage Cultivators" },
  { id: "M_CULTIVAT,N,12,0", label: "Male Cultivators" },
  { id: "F_CULTIVAT,N,11,0", label: "Female Cultivators" },
  { id: "SR_CULTIVA,N,12,0", label: "Sex Ratio Cultivators" },
  { id: "T_AGRI_LAB,N,12,0", label: "Total Agricultural Laborers" },
  { id: "T%_AGRI_LA,N,12,2", label: "Percentage Agricultural Laborers" },
  { id: "M_AGRI_LAB,N,12,0", label: "Male Agricultural Laborers" },
  { id: "F_AGRI_LAB,N,12,0", label: "Female Agricultural Laborers" },
  { id: "SR_AGRI_LA,N,12,0", label: "Sex Ratio Agricultural Laborers" },
  { id: "T_FISH_FOR,N,12,0", label: "Total Fishery Workers" },
  { id: "T%_FISH_FO,N,12,2", label: "Percentage Fishery Workers" },
  { id: "M_FISH_FOR,N,12,0", label: "Male Fishery Workers" },
  { id: "F_FISH_FOR,N,12,0", label: "Female Fishery Workers" },
  { id: "SR_FISH_FO,N,12,0", label: "Sex Ratio Fishery Workers" },
  { id: "T_MINING,N,10,0", label: "Total Mining Workers" },
  { id: "T%_MINING,N,12,2", label: "Percentage Mining Workers" },
  { id: "M_MINING,N,11,0", label: "Male Mining Workers" },
  { id: "F_MINING,N,10,0", label: "Female Mining Workers" },
  { id: "SR_MINING,N,12,0", label: "Sex Ratio Mining Workers" },
  { id: "T_HH_INDUS,N,12,0", label: "Total Household Industry Workers" },
  { id: "T%_HH_INDU,N,12,2", label: "Percentage Household Industry Workers" },
  { id: "M_HH_INDUS,N,12,0", label: "Male Household Industry Workers" },
  { id: "F_HH_INDUS,N,12,0", label: "Female Household Industry Workers" },
  { id: "SR_HH_INDU,N,12,0", label: "Sex Ratio Household Industry Workers" },
  { id: "T_OTH_INDU,N,12,0", label: "Total Other Industry Workers" },
  { id: "T%_OTH_IND,N,12,2", label: "Percentage Other Industry Workers" },
  { id: "M_OTH_INDU,N,12,0", label: "Male Other Industry Workers" },
  { id: "F_OTH_INDU,N,12,0", label: "Female Other Industry Workers" },
  { id: "SR_OTH_IND,N,12,0", label: "Sex Ratio Other Industry Workers" },
  { id: "T_CONSTRUC,N,13,0", label: "Total Construction Workers" },
  { id: "T%_CONSTRU,N,13,2", label: "Percentage Construction Workers" },
  { id: "M_CONSTRUC,N,13,0", label: "Male Construction Workers" },
  { id: "F_CONSTRUC,N,13,0", label: "Female Construction Workers" },
  { id: "SR_CONSTRU,N,13,0", label: "Sex Ratio Construction Workers" },
  { id: "T_TRADE,N,10,0", label: "Total Trade Workers" },
  { id: "T%_TRADE,N,12,2", label: "Percentage Trade Workers" },
  { id: "M_TRADE,N,10,0", label: "Male Trade Workers" },
  { id: "F_TRADE,N,10,0", label: "Female Trade Workers" },
  { id: "SR_TRADE,N,11,0", label: "Sex Ratio Trade Workers" },
  { id: "T_TRANSPOR,N,13,0", label: "Total Transport Workers" },
  { id: "T%_TRANSPO,N,13,2", label: "Percentage Transport Workers" },
  { id: "M_TRANSPOR,N,13,0", label: "Male Transport Workers" },
  { id: "F_TRANSPOR,N,13,0", label: "Female Transport Workers" },
  { id: "SR_TRANSPO,N,13,0", label: "Sex Ratio Transport Workers" },
  { id: "T_SERVICES,N,12,0", label: "Total Service Workers" },
  { id: "T%_SERVICE,N,13,2", label: "Percentage Service Workers" },
  { id: "M_SERVICES,N,13,0", label: "Male Service Workers" },
  { id: "F_SERVICES,N,12,0", label: "Female Service Workers" },
  { id: "SR_SERVICE,N,12,0", label: "Sex Ratio Service Workers" },
];

const urban_1991 = [
 
  { id: "T_POPULAT°,N,12,0", label: "Total Population" },
  { id: "DENSITY,N,9,0", label: "Density" },
  { id: "HOUSEHOLDS,N,14,0", label: "Households" },
  { id: "PERS/HOUSE,N,13,1", label: "Persons per Household" },
  { id: "MALE_POP,N,11,0", label: "Male Population" },
  { id: "FEMALE_POP,N,13,0", label: "Female Population" },
  { id: "SR_POPULAT,N,13,0", label: "Sex Ratio" },
  { id: "T_CHILDREN,N,12,0", label: "Total Children" },
  { id: "M_CHILDREN,N,12,0", label: "Male Children" },
  { id: "F_CHILDREN,N,12,0", label: "Female Children" },
  { id: "SR_CHILDRE,N,12,0", label: "Sex Ratio Children" },
  { id: "T_SC,N,5,0", label: "Total SC" },
  { id: "T%_SC,N,7,1", label: "Percentage SC" },
  { id: "M_SC,N,6,0", label: "Male SC" },
  { id: "F_SC,N,5,0", label: "Female SC" },
  { id: "SR_SC,N,7,0", label: "Sex Ratio SC" },
  { id: "T_ST,N,5,0", label: "Total ST" },
  { id: "T%_ST,N,7,1", label: "Percentage ST" },
  { id: "M_ST,N,6,0", label: "Male ST" },
  { id: "F_ST,N,5,0", label: "Female ST" },
  { id: "SR_ST,N,7,0", label: "Sex Ratio ST" },
  { id: "T_LITTERAT,N,11,0", label: "Total Literate" },
  { id: "T%_LITTERA,N,12,1", label: "Percentage Literate" },
  { id: "M_LITTERAT,N,12,0", label: "Male Literate" },
  { id: "F_LITTERAT,N,11,0", label: "Female Literate" },
  { id: "SR_LITTERA,N,12,0", label: "Sex Ratio Literate" },
  { id: "T_WORKERS,N,12,0", label: "Total Workers" },
  { id: "T%_WORKERS,N,14,1", label: "Percentage Workers" },
  { id: "M_WORKERS,N,13,0", label: "Male Workers" },
  { id: "F_WORKERS,N,13,0", label: "Female Workers" },
  { id: "SR_WORKERS,N,14,0", label: "Sex Ratio Workers" },
  { id: "T_MARGINAL,N,12,0", label: "Total Marginal Workers" },
  { id: "T%_MARGINA,N,13,1", label: "Percentage Marginal Workers" },
  { id: "M_MARGINAL,N,13,0", label: "Male Marginal Workers" },
  { id: "F_MARGINAL,N,12,0", label: "Female Marginal Workers" },
  { id: "SR_MARGINA,N,13,0", label: "Sex Ratio Marginal Workers" },
  { id: "T_NONWORK,N,13,0", label: "Total Non-Workers" },
  { id: "T%_NONWORK,N,14,1", label: "Percentage Non-Workers" },
  { id: "M_NONWORK,N,13,0", label: "Male Non-Workers" },
  { id: "F_NONWORK,N,13,0", label: "Female Non-Workers" },
  { id: "SR_NONWORK,N,14,0", label: "Sex Ratio Non-Workers" },
  { id: "T_PRIMARY,N,11,0", label: "Total Primary Workers" },
  { id: "T%_PRIMARY,N,13,1", label: "Percentage Primary Workers" },
  { id: "M_PRIMARY,N,12,0", label: "Male Primary Workers" },
  { id: "F_PRIMARY,N,11,0", label: "Female Primary Workers" },
  { id: "SR_PRIMARY,N,13,0", label: "Sex Ratio Primary Workers" },
  { id: "T_SECUND,N,10,0", label: "Total Secondary Workers" },
  { id: "T%_SECUND,N,12,1", label: "Percentage Secondary Workers" },
  { id: "M_SECUND,N,11,0", label: "Male Secondary Workers" },
  { id: "F_SECUND,N,11,0", label: "Female Secondary Workers" },
  { id: "SR_SECUND,N,12,0", label: "Sex Ratio Secondary Workers" },
  { id: "T_TERTIARY,N,12,0", label: "Total Tertiary Workers" },
  { id: "T%_TERTIAR,N,12,1", label: "Percentage Tertiary Workers" },
  { id: "M_TERTIARY,N,12,0", label: "Male Tertiary Workers" },
  { id: "F_TERTIARY,N,12,0", label: "Female Tertiary Workers" },
  { id: "SR_TERTIAR,N,12,0", label: "Sex Ratio Tertiary Workers" },
  { id: "T_CULTIVAT,N,11,0", label: "Total Cultivators" },
  { id: "T%_CULTIVA,N,12,1", label: "Percentage Cultivators" },
  { id: "M_CULTIVAT,N,12,0", label: "Male Cultivators" },
  { id: "F_CULTIVAT,N,11,0", label: "Female Cultivators" },
  { id: "SR_CULTIVA,N,12,0", label: "Sex Ratio Cultivators" },
  { id: "T_AGRI_LAB,N,12,0", label: "Total Agricultural Laborers" },
  { id: "T%_AGRI_LA,N,12,1", label: "Percentage Agricultural Laborers" },
  { id: "M_AGRI_LAB,N,12,0", label: "Male Agricultural Laborers" },
  { id: "F_AGRI_LAB,N,12,0", label: "Female Agricultural Laborers" },
  { id: "SR_AGRI_LA,N,12,0", label: "Sex Ratio Agricultural Laborers" },
  { id: "T_FISH_FOR,N,12,0", label: "Total Fishery Workers" },
  { id: "T%_FISH_FO,N,12,1", label: "Percentage Fishery Workers" },
  { id: "M_FISH_FOR,N,12,0", label: "Male Fishery Workers" },
  { id: "F_FISH_FOR,N,12,0", label: "Female Fishery Workers" },
  { id: "SR_FISH_FO,N,12,0", label: "Sex Ratio Fishery Workers" },
  { id: "T_MINING,N,9,0", label: "Total Mining Workers" },
  { id: "T%_MINING,N,11,1", label: "Percentage Mining Workers" },
  { id: "M_MINING,N,10,0", label: "Male Mining Workers" },
  { id: "F_MINING,N,9,0", label: "Female Mining Workers" },
  { id: "SR_MINING,N,11,0", label: "Sex Ratio Mining Workers" },
  { id: "T_HH_INDUS,N,12,0", label: "Total Household Industry Workers" },
  { id: "T%_HH_INDU,N,12,1", label: "Percentage Household Industry Workers" },
  { id: "M_HH_INDUS,N,12,0", label: "Male Household Industry Workers" },
  { id: "F_HH_INDUS,N,12,0", label: "Female Household Industry Workers" },
  { id: "SR_HH_INDU,N,12,0", label: "Sex Ratio Household Industry Workers" },
  { id: "T_OTH_INDU,N,12,0", label: "Total Other Industry Workers" },
  { id: "T%_OTH_IND,N,12,1", label: "Percentage Other Industry Workers" },
  { id: "M_OTH_INDU,N,12,0", label: "Male Other Industry Workers" },
  { id: "F_OTH_INDU,N,12,0", label: "Female Other Industry Workers" },
  { id: "SR_OTH_IND,N,12,0", label: "Sex Ratio Other Industry Workers" },
  { id: "T_CONSTRUC,N,13,0", label: "Total Construction Workers" },
  { id: "T%_CONSTRU,N,13,1", label: "Percentage Construction Workers" },
  { id: "M_CONSTRUC,N,13,0", label: "Male Construction Workers" },
  { id: "F_CONSTRUC,N,13,0", label: "Female Construction Workers" },
  { id: "SR_CONSTRU,N,13,0", label: "Sex Ratio Construction Workers" },
  { id: "T_TRADE,N,10,0", label: "Total Trade Workers" },
  { id: "T%_TRADE,N,11,1", label: "Percentage Trade Workers" },
  { id: "M_TRADE,N,9,0", label: "Male Trade Workers" },
  { id: "F_TRADE,N,9,0", label: "Female Trade Workers" },
  { id: "SR_TRADE,N,10,0", label: "Sex Ratio Trade Workers" },
  { id: "T_TRANSPOR,N,13,0", label: "Total Transport Workers" },
  { id: "T%_TRANSPO,N,13,1", label: "Percentage Transport Workers" },
  { id: "M_TRANSPOR,N,13,0", label: "Male Transport Workers" },
  { id: "F_TRANSPOR,N,13,0", label: "Female Transport Workers" },
  { id: "SR_TRANSPO,N,13,0", label: "Sex Ratio Transport Workers" },
  { id: "T_SERVICES,N,12,0", label: "Total Service Workers" },
  { id: "T%_SERVICE,N,13,1", label: "Percentage Service Workers" },
  { id: "M_SERVICES,N,13,0", label: "Male Service Workers" },
  { id: "F_SERVICES,N,12,0", label: "Female Service Workers" },
  { id: "SR_SERVICE,N,12,0", label: "Sex Ratio Service Workers" },
];

const dt_rur_1991 = [

  { id: "T_POPULAT°,N,12,0", label: "Total Population" },
  { id: "DENSITY,N,9,0", label: "Density" },
  { id: "HOUSEHOLDS,N,14,0", label: "Households" },
  { id: "PERS/HOUSE,N,13,1", label: "Persons per Household" },
  { id: "MALE_POP,N,11,0", label: "Male Population" },
  { id: "FEMALE_POP,N,13,0", label: "Female Population" },
  { id: "SR_POPULAT,N,13,0", label: "Sex Ratio" },
  { id: "T_CHILDREN,N,12,0", label: "Total Children" },
  { id: "M_CHILDREN,N,12,0", label: "Male Children" },
  { id: "F_CHILDREN,N,12,0", label: "Female Children" },
  { id: "SR_CHILDRE,N,12,0", label: "Sex Ratio Children" },
  { id: "T_SC,N,8,0", label: "Total SC" },
  { id: "T%_SC,N,7,2", label: "Percentage SC" },
  { id: "M_SC,N,7,0", label: "Male SC" },
  { id: "F_SC,N,7,0", label: "Female SC" },
  { id: "SR_SC,N,7,0", label: "Sex Ratio SC" },
  { id: "T_ST,N,7,0", label: "Total ST" },
  { id: "T%_ST,N,7,2", label: "Percentage ST" },
  { id: "M_ST,N,6,0", label: "Male ST" },
  { id: "F_ST,N,6,0", label: "Female ST" },
  { id: "SR_ST,N,7,0", label: "Sex Ratio ST" },
  { id: "T_LITTERAT,N,11,0", label: "Total Literate" },
  { id: "T%_LITTERA,N,12,2", label: "Percentage Literate" },
  { id: "M_LITTERAT,N,12,0", label: "Male Literate" },
  { id: "F_LITTERAT,N,11,0", label: "Female Literate" },
  { id: "SR_LITTERA,N,12,0", label: "Sex Ratio Literate" },
  { id: "T_WORKERS,N,12,0", label: "Total Workers" },
  { id: "T%_WORKERS,N,14,2", label: "Percentage Workers" },
  { id: "M_WORKERS,N,13,0", label: "Male Workers" },
  { id: "F_WORKERS,N,13,0", label: "Female Workers" },
  { id: "SR_WORKERS,N,14,0", label: "Sex Ratio Workers" },
  { id: "T_MARGINAL,N,12,0", label: "Total Marginal Workers" },
  { id: "T%_MARGINA,N,13,2", label: "Percentage Marginal Workers" },
  { id: "M_MARGINAL,N,13,0", label: "Male Marginal Workers" },
  { id: "F_MARGINAL,N,12,0", label: "Female Marginal Workers" },
  { id: "SR_MARGINA,N,13,0", label: "Sex Ratio Marginal Workers" },
  { id: "T_NONWORK,N,13,0", label: "Total Non-Workers" },
  { id: "T%_NONWORK,N,14,2", label: "Percentage Non-Workers" },
  { id: "M_NONWORK,N,13,0", label: "Male Non-Workers" },
  { id: "F_NONWORK,N,13,0", label: "Female Non-Workers" },
  { id: "SR_NONWORK,N,14,0", label: "Sex Ratio Non-Workers" },
  { id: "T_PRIMARY,N,11,0", label: "Total Primary Workers" },
  { id: "T%_PRIMARY,N,13,2", label: "Percentage Primary Workers" },
  { id: "M_PRIMARY,N,12,0", label: "Male Primary Workers" },
  { id: "F_PRIMARY,N,11,0", label: "Female Primary Workers" },
  { id: "SR_PRIMARY,N,13,0", label: "Sex Ratio Primary Workers" },
  { id: "T_SECUND,N,10,0", label: "Total Secondary Workers" },
  { id: "T%_SECUND,N,12,2", label: "Percentage Secondary Workers" },
  { id: "M_SECUND,N,11,0", label: "Male Secondary Workers" },
  { id: "F_SECUND,N,11,0", label: "Female Secondary Workers" },
  { id: "SR_SECUND,N,12,0", label: "Sex Ratio Secondary Workers" },
  { id: "T_TERTIARY,N,12,0", label: "Total Tertiary Workers" },
  { id: "T%_TERTIAR,N,12,2", label: "Percentage Tertiary Workers" },
  { id: "M_TERTIARY,N,12,0", label: "Male Tertiary Workers" },
  { id: "F_TERTIARY,N,12,0", label: "Female Tertiary Workers" },
  { id: "SR_TERTIAR,N,12,0", label: "Sex Ratio Tertiary Workers" },
  { id: "T_CULTIVAT,N,11,0", label: "Total Cultivators" },
  { id: "T%_CULTIVA,N,12,2", label: "Percentage Cultivators" },
  { id: "M_CULTIVAT,N,12,0", label: "Male Cultivators" },
  { id: "F_CULTIVAT,N,11,0", label: "Female Cultivators" },
  { id: "SR_CULTIVA,N,12,0", label: "Sex Ratio Cultivators" },
  { id: "T_AGRI_LAB,N,12,0", label: "Total Agricultural Laborers" },
  { id: "T%_AGRI_LA,N,12,2", label: "Percentage Agricultural Laborers" },
  { id: "M_AGRI_LAB,N,12,0", label: "Male Agricultural Laborers" },
  { id: "F_AGRI_LAB,N,12,0", label: "Female Agricultural Laborers" },
  { id: "SR_AGRI_LA,N,12,0", label: "Sex Ratio Agricultural Laborers" },
  { id: "T_FISH_FOR,N,12,0", label: "Total Fishery Workers" },
  { id: "T%_FISH_FO,N,12,2", label: "Percentage Fishery Workers" },
  { id: "M_FISH_FOR,N,12,0", label: "Male Fishery Workers" },
  { id: "F_FISH_FOR,N,12,0", label: "Female Fishery Workers" },
  { id: "SR_FISH_FO,N,12,0", label: "Sex Ratio Fishery Workers" },
  { id: "T_MINING,N,9,0", label: "Total Mining Workers" },
  { id: "T%_MINING,N,11,2", label: "Percentage Mining Workers" },
  { id: "M_MINING,N,10,0", label: "Male Mining Workers" },
  { id: "F_MINING,N,9,0", label: "Female Mining Workers" },
  { id: "SR_MINING,N,11,0", label: "Sex Ratio Mining Workers" },
  { id: "T_HH_INDUS,N,12,0", label: "Total Household Industry Workers" },
  { id: "T%_HH_INDU,N,12,2", label: "Percentage Household Industry Workers" },
  { id: "M_HH_INDUS,N,12,0", label: "Male Household Industry Workers" },
  { id: "F_HH_INDUS,N,12,0", label: "Female Household Industry Workers" },
  { id: "SR_HH_INDU,N,12,0", label: "Sex Ratio Household Industry Workers" },
  { id: "T_OTH_INDU,N,12,0", label: "Total Other Industry Workers" },
  { id: "T%_OTH_IND,N,12,2", label: "Percentage Other Industry Workers" },
  { id: "M_OTH_INDU,N,12,0", label: "Male Other Industry Workers" },
  { id: "F_OTH_INDU,N,12,0", label: "Female Other Industry Workers" },
  { id: "SR_OTH_IND,N,12,0", label: "Sex Ratio Other Industry Workers" },
  { id: "T_CONSTRUC,N,13,0", label: "Total Construction Workers" },
  { id: "T%_CONSTRU,N,13,2", label: "Percentage Construction Workers" },
  { id: "M_CONSTRUC,N,13,0", label: "Male Construction Workers" },
  { id: "F_CONSTRUC,N,13,0", label: "Female Construction Workers" },
  { id: "SR_CONSTRU,N,13,0", label: "Sex Ratio Construction Workers" },
  { id: "T_TRADE,N,9,0", label: "Total Trade Workers" },
  { id: "T%_TRADE,N,11,2", label: "Percentage Trade Workers" },
  { id: "M_TRADE,N,9,0", label: "Male Trade Workers" },
  { id: "F_TRADE,N,9,0", label: "Female Trade Workers" },
  { id: "SR_TRADE,N,10,0", label: "Sex Ratio Trade Workers" },
  { id: "T_TRANSPOR,N,13,0", label: "Total Transport Workers" },
  { id: "T%_TRANSPO,N,13,2", label: "Percentage Transport Workers" },
  { id: "M_TRANSPOR,N,13,0", label: "Male Transport Workers" },
  { id: "F_TRANSPOR,N,13,0", label: "Female Transport Workers" },
  { id: "SR_TRANSPO,N,13,0", label: "Sex Ratio Transport Workers" },
  { id: "T_SERVICES,N,12,0", label: "Total Service Workers" },
  { id: "T%_SERVICE,N,13,2", label: "Percentage Service Workers" },
  { id: "M_SERVICES,N,13,0", label: "Male Service Workers" },
  { id: "F_SERVICES,N,12,0", label: "Female Service Workers" },
  { id: "SR_SERVICE,N,12,0", label: "Sex Ratio Service Workers" },
];

const taluk_1991 = [

  { id: "T_POPULAT°,N,12,0", label: "Total Population" },
  { id: "DENSITY,N,9,0", label: "Density" },
  { id: "HOUSEHOLDS,N,14,0", label: "Households" },
  { id: "PERS/HOUSE,N,13,1", label: "Persons per Household" },
  { id: "MALE_POP,N,11,0", label: "Male Population" },
  { id: "FEMALE_POP,N,13,0", label: "Female Population" },
  { id: "SR_POPULAT,N,13,0", label: "Sex Ratio" },
  { id: "T_CHILDREN,N,12,0", label: "Total Children" },
  { id: "M_CHILDREN,N,12,0", label: "Male Children" },
  { id: "F_CHILDREN,N,12,0", label: "Female Children" },
  { id: "SR_CHILDRE,N,12,0", label: "Sex Ratio Children" },
  { id: "T_SC,N,7,0", label: "Total SC" },
  { id: "T%_SC,N,7,2", label: "Percentage SC" },
  { id: "M_SC,N,12,0", label: "Male SC" },
  { id: "F_SC,N,12,0", label: "Female SC" },
  { id: "SR_SC,N,12,0", label: "Sex Ratio SC" },
  { id: "T_ST,N,12,0", label: "Total ST" },
  { id: "T%_ST,N,7,2", label: "Percentage ST" },
  { id: "M_ST,N,12,0", label: "Male ST" },
  { id: "F_ST,N,12,0", label: "Female ST" },
  { id: "SR_ST,N,12,0", label: "Sex Ratio ST" },
  { id: "T_LITTERAT,N,12,0", label: "Total Literate" },
  { id: "T%_LITTERA,N,12,2", label: "Percentage Literate" },
  { id: "M_LITTERAT,N,12,0", label: "Male Literate" },
  { id: "F_LITTERAT,N,12,0", label: "Female Literate" },
  { id: "SR_LITTERA,N,12,0", label: "Sex Ratio Literate" },
  { id: "T_WORKERS,N,12,0", label: "Total Workers" },
  { id: "T%_WORKERS,N,14,2", label: "Percentage Workers" },
  { id: "M_WORKERS,N,12,0", label: "Male Workers" },
  { id: "F_WORKERS,N,12,0", label: "Female Workers" },
  { id: "SR_WORKERS,N,12,0", label: "Sex Ratio Workers" },
  { id: "T_MARGINAL,N,12,0", label: "Total Marginal Workers" },
  { id: "T%_MARGINA,N,13,2", label: "Percentage Marginal Workers" },
  { id: "M_MARGINAL,N,12,0", label: "Male Marginal Workers" },
  { id: "F_MARGINAL,N,12,0", label: "Female Marginal Workers" },
  { id: "SR_MARGINA,N,12,0", label: "Sex Ratio Marginal Workers" },
  { id: "T_NONWORK,N,12,0", label: "Total Non-Workers" },
  { id: "T%_NONWORK,N,14,2", label: "Percentage Non-Workers" },
  { id: "M_NONWORK,N,12,0", label: "Male Non-Workers" },
  { id: "F_NONWORK,N,12,0", label: "Female Non-Workers" },
  { id: "SR_NONWORK,N,12,0", label: "Sex Ratio Non-Workers" },
  { id: "T_PRIMARY,N,12,0", label: "Total Primary Workers" },
  { id: "T%_PRIMARY,N,13,2", label: "Percentage Primary Workers" },
  { id: "M_PRIMARY,N,12,0", label: "Male Primary Workers" },
  { id: "F_PRIMARY,N,12,0", label: "Female Primary Workers" },
  { id: "SR_PRIMARY,N,12,0", label: "Sex Ratio Primary Workers" },
  { id: "T_SECUND,N,12,0", label: "Total Secondary Workers" },
  { id: "T%_SECUND,N,12,2", label: "Percentage Secondary Workers" },
  { id: "M_SECUND,N,12,0", label: "Male Secondary Workers" },
  { id: "F_SECUND,N,12,0", label: "Female Secondary Workers" },
  { id: "SR_SECUND,N,12,0", label: "Sex Ratio Secondary Workers" },
  { id: "T_TERTIARY,N,12,0", label: "Total Tertiary Workers" },
  { id: "T%_TERTIAR,N,12,2", label: "Percentage Tertiary Workers" },
  { id: "M_TERTIARY,N,12,0", label: "Male Tertiary Workers" },
  { id: "F_TERTIARY,N,12,0", label: "Female Tertiary Workers" },
  { id: "SR_TERTIAR,N,12,0", label: "Sex Ratio Tertiary Workers" },
  { id: "T_CULTIVAT,N,12,0", label: "Total Cultivators" },
  { id: "T%_CULTIVA,N,12,2", label: "Percentage Cultivators" },
  { id: "M_CULTIVAT,N,12,0", label: "Male Cultivators" },
  { id: "F_CULTIVAT,N,12,0", label: "Female Cultivators" },
  { id: "SR_CULTIVA,N,12,0", label: "Sex Ratio Cultivators" },
  { id: "T_AGRI_LAB,N,12,0", label: "Total Agricultural Laborers" },
  { id: "T%_AGRI_LA,N,12,2", label: "Percentage Agricultural Laborers" },
  { id: "M_AGRI_LAB,N,12,0", label: "Male Agricultural Laborers" },
  { id: "F_AGRI_LAB,N,12,0", label: "Female Agricultural Laborers" },
  { id: "SR_AGRI_LA,N,12,0", label: "Sex Ratio Agricultural Laborers" },
  { id: "T_FISH_FOR,N,12,0", label: "Total Fishery Workers" },
  { id: "T%_FISH_FO,N,12,2", label: "Percentage Fishery Workers" },
  { id: "M_FISH_FOR,N,12,0", label: "Male Fishery Workers" },
  { id: "F_FISH_FOR,N,12,0", label: "Female Fishery Workers" },
  { id: "SR_FISH_FO,N,12,0", label: "Sex Ratio Fishery Workers" },
  { id: "T_MINING,N,12,0", label: "Total Mining Workers" },
  { id: "T%_MINING,N,11,2", label: "Percentage Mining Workers" },
  { id: "M_MINING,N,12,0", label: "Male Mining Workers" },
  { id: "F_MINING,N,12,0", label: "Female Mining Workers" },
  { id: "SR_MINING,N,12,0", label: "Sex Ratio Mining Workers" },
  { id: "T_HH_INDUS,N,12,0", label: "Total Household Industry Workers" },
  { id: "T%_HH_INDU,N,12,2", label: "Percentage Household Industry Workers" },
  { id: "M_HH_INDUS,N,12,0", label: "Male Household Industry Workers" },
  { id: "F_HH_INDUS,N,12,0", label: "Female Household Industry Workers" },
  { id: "SR_HH_INDU,N,12,0", label: "Sex Ratio Household Industry Workers" },
  { id: "T_OTH_INDU,N,12,0", label: "Total Other Industry Workers" },
  { id: "T%_OTH_IND,N,12,2", label: "Percentage Other Industry Workers" },
  { id: "M_OTH_INDU,N,12,0", label: "Male Other Industry Workers" },
  { id: "F_OTH_INDU,N,12,0", label: "Female Other Industry Workers" },
  { id: "SR_OTH_IND,N,12,0", label: "Sex Ratio Other Industry Workers" },
  { id: "T_CONSTRUC,N,12,0", label: "Total Construction Workers" },
  { id: "T%_CONSTRU,N,13,2", label: "Percentage Construction Workers" },
  { id: "M_CONSTRUC,N,12,0", label: "Male Construction Workers" },
  { id: "F_CONSTRUC,N,12,0", label: "Female Construction Workers" },
  { id: "SR_CONSTRU,N,12,0", label: "Sex Ratio Construction Workers" },
  { id: "T_TRADE,N,12,0", label: "Total Trade Workers" },
  { id: "T%_TRADE,N,11,2", label: "Percentage Trade Workers" },
  { id: "M_TRADE,N,12,0", label: "Male Trade Workers" },
  { id: "F_TRADE,N,12,0", label: "Female Trade Workers" },
  { id: "SR_TRADE,N,12,0", label: "Sex Ratio Trade Workers" },
  { id: "T_TRANSPOR,N,12,0", label: "Total Transport Workers" },
  { id: "T%_TRANSPO,N,13,2", label: "Percentage Transport Workers" },
  { id: "M_TRANSPOR,N,12,0", label: "Male Transport Workers" },
  { id: "F_TRANSPOR,N,12,0", label: "Female Transport Workers" },
  { id: "SR_TRANSPO,N,12,0", label: "Sex Ratio Transport Workers" },
  { id: "T_SERVICES,N,12,0", label: "Total Service Workers" },
  { id: "T%_SERVICE,N,13,2", label: "Percentage Service Workers" },
  { id: "M_SERVICES,N,12,0", label: "Male Service Workers" },
  { id: "F_SERVICES,N,12,0", label: "Female Service Workers" },
  { id: "SR_SERVICE,N,12,0", label: "Sex Ratio Service Workers" },
  { id: "LU_FOREST,N,11,2", label: "Land Use Forest" },
  { id: "LU%_FOREST,N,13,2", label: "Percentage Land Use Forest" },
  { id: "LU_IRRIGAT,N,11,2", label: "Land Use Irrigated" },
  { id: "LU%_IRRIGA,N,12,2", label: "Percentage Land Use Irrigated" },
  { id: "LU_UNIRRIG,N,11,2", label: "Land Use Unirrigated" },
  { id: "LU%_UNIRRI,N,12,2", label: "Percentage Land Use Unirrigated" },
  { id: "LU_CULT_WA,N,13,2", label: "Land Use Cultivable Waste" },
  { id: "LU%_CULT_W,N,13,2", label: "Percentage Land Use Cultivable Waste" },
  { id: "LU_NON_CUL,N,13,2", label: "Land Use Non-Cultivable" },
  { id: "LU%_NON_C,N,12,2", label: "Percentage Land Use Non-Cultivable" },
  { id: "IR_WELL,N,9,2", label: "Irrigation Well" },
  { id: "IR_TUBEWEL,N,12,2", label: "Irrigation Tube Well" },
  { id: "IR_TANK,N,8,2", label: "Irrigation Tank" },
  { id: "IR_LAKE,N,8,2", label: "Irrigation Lake" },
  { id: "IR_RIVER,N,9,2", label: "Irrigation River" },
  { id: "IR_GVT_CAN,N,12,2", label: "Irrigation Government Canal" },
  { id: "IR_PRIV_CA,N,11,2", label: "Irrigation Private Canal" },
  { id: "IR_OTHER,N,10,2", label: "Irrigation Other" },
];

const village_1991 = [
 
  { id: "T_POPULAT°,N,12,0", label: "Total Population" },
  { id: "DENSITY,N,9,0", label: "Density" },
  { id: "HOUSEHOLDS,N,14,0", label: "Households" },
  { id: "PERS/HOUSE,N,13,1", label: "Persons per Household" },
  { id: "MALE_POP,N,11,0", label: "Male Population" },
  { id: "FEMALE_POP,N,13,0", label: "Female Population" },
  { id: "SR_POPULAT,N,13,0", label: "Sex Ratio" },
  { id: "T_CHILDREN,N,12,0", label: "Total Children" },
  { id: "M_CHILDREN,N,12,0", label: "Male Children" },
  { id: "F_CHILDREN,N,12,0", label: "Female Children" },
  { id: "SR_CHILDRE,N,12,0", label: "Sex Ratio Children" },
  { id: "T_SC,N,6,0", label: "Total SC" },
  { id: "T%_SC,N,7,1", label: "Percentage SC" },
  { id: "M_SC,N,6,0", label: "Male SC" },
  { id: "F_SC,N,5,0", label: "Female SC" },
  { id: "SR_SC,N,7,0", label: "Sex Ratio SC" },
  { id: "T_ST,N,5,0", label: "Total ST" },
  { id: "T%_ST,N,7,1", label: "Percentage ST" },
  { id: "M_ST,N,6,0", label: "Male ST" },
  { id: "F_ST,N,5,0", label: "Female ST" },
  { id: "SR_ST,N,7,0", label: "Sex Ratio ST" },
  { id: "T_LITTERAT,N,11,0", label: "Total Literate" },
  { id: "T%_LITTERA,N,12,2", label: "Percentage Literate" },
  { id: "M_LITTERAT,N,12,0", label: "Male Literate" },
  { id: "F_LITTERAT,N,11,0", label: "Female Literate" },
  { id: "SR_LITTERA,N,12,0", label: "Sex Ratio Literate" },
  { id: "T_WORKERS,N,12,0", label: "Total Workers" },
  { id: "T%_WORKERS,N,14,1", label: "Percentage Workers" },
  { id: "M_WORKERS,N,13,0", label: "Male Workers" },
  { id: "F_WORKERS,N,13,0", label: "Female Workers" },
  { id: "SR_WORKERS,N,14,0", label: "Sex Ratio Workers" },
  { id: "T_MARGINAL,N,12,0", label: "Total Marginal Workers" },
  { id: "T%_MARGINA,N,13,1", label: "Percentage Marginal Workers" },
  { id: "M_MARGINAL,N,13,0", label: "Male Marginal Workers" },
  { id: "F_MARGINAL,N,12,0", label: "Female Marginal Workers" },
  { id: "SR_MARGINA,N,13,0", label: "Sex Ratio Marginal Workers" },
  { id: "T_NONWORK,N,13,0", label: "Total Non-Workers" },
  { id: "T%_NONWORK,N,14,1", label: "Percentage Non-Workers" },
  { id: "M_NONWORK,N,13,0", label: "Male Non-Workers" },
  { id: "F_NONWORK,N,13,0", label: "Female Non-Workers" },
  { id: "SR_NONWORK,N,14,0", label: "Sex Ratio Non-Workers" },
  { id: "T_PRIMARY,N,11,0", label: "Total Primary Workers" },
  { id: "T%_PRIMARY,N,13,2", label: "Percentage Primary Workers" },
  { id: "M_PRIMARY,N,12,0", label: "Male Primary Workers" },
  { id: "F_PRIMARY,N,11,0", label: "Female Primary Workers" },
  { id: "SR_PRIMARY,N,13,0", label: "Sex Ratio Primary Workers" },
  { id: "T_SECUND,N,10,0", label: "Total Secondary Workers" },
  { id: "T%_SECUND,N,12,2", label: "Percentage Secondary Workers" },
  { id: "M_SECUND,N,11,0", label: "Male Secondary Workers" },
  { id: "F_SECUND,N,11,0", label: "Female Secondary Workers" },
  { id: "SR_SECUND,N,12,0", label: "Sex Ratio Secondary Workers" },
  { id: "T_TERTIARY,N,12,0", label: "Total Tertiary Workers" },
  { id: "T%_TERTIAR,N,12,2", label: "Percentage Tertiary Workers" },
  { id: "M_TERTIARY,N,12,0", label: "Male Tertiary Workers" },
  { id: "F_TERTIARY,N,12,0", label: "Female Tertiary Workers" },
  { id: "SR_TERTIAR,N,12,0", label: "Sex Ratio Tertiary Workers" },
  { id: "T_CULTIVAT,N,11,0", label: "Total Cultivators" },
  { id: "T%_CULTIVA,N,12,2", label: "Percentage Cultivators" },
  { id: "M_CULTIVAT,N,12,0", label: "Male Cultivators" },
  { id: "F_CULTIVAT,N,11,0", label: "Female Cultivators" },
  { id: "SR_CULTIVA,N,12,0", label: "Sex Ratio Cultivators" },
  { id: "T_AGRI_LAB,N,12,0", label: "Total Agricultural Laborers" },
  { id: "T%_AGRI_LA,N,12,2", label: "Percentage Agricultural Laborers" },
  { id: "M_AGRI_LAB,N,12,0", label: "Male Agricultural Laborers" },
  { id: "F_AGRI_LAB,N,12,0", label: "Female Agricultural Laborers" },
  { id: "SR_AGRI_LA,N,12,0", label: "Sex Ratio Agricultural Laborers" },
  { id: "T_FISH_FOR,N,12,0", label: "Total Fishery Workers" },
  { id: "T%_FISH_FO,N,12,2", label: "Percentage Fishery Workers" },
  { id: "M_FISH_FOR,N,12,0", label: "Male Fishery Workers" },
  { id: "F_FISH_FOR,N,12,0", label: "Female Fishery Workers" },
  { id: "SR_FISH_FO,N,12,0", label: "Sex Ratio Fishery Workers" },
  { id: "T_MINING,N,9,0", label: "Total Mining Workers" },
  { id: "T%_MINING,N,12,2", label: "Percentage Mining Workers" },
  { id: "M_MINING,N,11,0", label: "Male Mining Workers" },
  { id: "F_MINING,N,10,0", label: "Female Mining Workers" },
  { id: "SR_MINING,N,12,0", label: "Sex Ratio Mining Workers" },
  { id: "T_HH_INDUS,N,12,0", label: "Total Household Industry Workers" },
  { id: "T%_HH_INDU,N,12,2", label: "Percentage Household Industry Workers" },
  { id: "M_HH_INDUS,N,12,0", label: "Male Household Industry Workers" },
  { id: "F_HH_INDUS,N,12,0", label: "Female Household Industry Workers" },
  { id: "SR_HH_INDU,N,12,0", label: "Sex Ratio Household Industry Workers" },
  { id: "T_OTH_INDU,N,12,0", label: "Total Other Industry Workers" },
  { id: "T%_OTH_IND,N,12,2", label: "Percentage Other Industry Workers" },
  { id: "M_OTH_INDU,N,12,0", label: "Male Other Industry Workers" },
  { id: "F_OTH_INDU,N,12,0", label: "Female Other Industry Workers" },
  { id: "SR_OTH_IND,N,12,0", label: "Sex Ratio Other Industry Workers" },
  { id: "T_CONSTRUC,N,13,0", label: "Total Construction Workers" },
  { id: "T%_CONSTRU,N,13,2", label: "Percentage Construction Workers" },
  { id: "M_CONSTRUC,N,13,0", label: "Male Construction Workers" },
  { id: "F_CONSTRUC,N,13,0", label: "Female Construction Workers" },
  { id: "SR_CONSTRU,N,13,0", label: "Sex Ratio Construction Workers" },
  { id: "T_TRADE,N,10,0", label: "Total Trade Workers" },
  { id: "T%_TRADE,N,12,2", label: "Percentage Trade Workers" },
  { id: "M_TRADE,N,10,0", label: "Male Trade Workers" },
  { id: "F_TRADE,N,10,0", label: "Female Trade Workers" },
  { id: "SR_TRADE,N,11,0", label: "Sex Ratio Trade Workers" },
  { id: "T_TRANSPOR,N,13,0", label: "Total Transport Workers" },
  { id: "T%_TRANSPO,N,13,2", label: "Percentage Transport Workers" },
  { id: "M_TRANSPOR,N,13,0", label: "Male Transport Workers" },
  { id: "F_TRANSPOR,N,13,0", label: "Female Transport Workers" },
  { id: "SR_TRANSPO,N,13,0", label: "Sex Ratio Transport Workers" },
  { id: "T_SERVICES,N,12,0", label: "Total Service Workers" },
  { id: "T%_SERVICE,N,13,2", label: "Percentage Service Workers" },
  { id: "M_SERVICES,N,13,0", label: "Male Service Workers" },
  { id: "F_SERVICES,N,12,0", label: "Female Service Workers" },
  { id: "SR_SERVICE,N,12,0", label: "Sex Ratio Service Workers" },
  { id: "EI_AVALAIB,C,11", label: "Educational Institution Availability" },
  { id: "EI_DISTANC,N,11,0", label: "Distance to Educational Institution" },
  { id: "P_SCHOOL,N,11,0", label: "Primary School" },
  { id: "M_SCHOOL,N,11,0", label: "Middle School" },
  { id: "H_SCHOOL,N,11,0", label: "High School" },
  { id: "PU_COLLEGE,N,13,0", label: "PU College" },
  { id: "GR_COLLEGE,N,13,0", label: "Graduation College" },
  { id: "ADULT_LIT_,N,11,0", label: "Adult Literacy" },
  { id: "INDUS_SCH,N,11,0", label: "Industrial School" },
  { id: "TRAIN_SCH,N,11,0", label: "Training School" },
  { id: "OTHER_EI,N,10,0", label: "Other Educational Institution" },
  { id: "MI_AVALAIB,C,12", label: "Medical Institution Availability" },
  { id: "MI_DISTANC,N,12,0", label: "Distance to Medical Institution" },
  { id: "HOSPITAL,N,10,0", label: "Hospital" },
  { id: "MAT&CHI_WC,N,13,0", label: "Maternity and Child Welfare Center" },
  { id: "MATERNITY,N,11,0", label: "Maternity Home" },
  { id: "CHILD_W_C,N,11,0", label: "Child Welfare Center" },
  { id: "PRIM_H_C,N,10,0", label: "Primary Health Center" },
  { id: "HEQLTH_C,N,10,0", label: "Health Center" },
  { id: "PRIM_H_S_C,N,12,0", label: "Primary Health Sub-Center" },
  { id: "DISPENSARY,N,13,0", label: "Dispensary" },
  { id: "FP_C,N,5,0", label: "Family Planning Center" },
  { id: "TB_C,N,5,0", label: "Tuberculosis Center" },
  { id: "NURSING_H,N,11,0", label: "Nursing Home" },
  { id: "CHWC,N,6,0", label: "Community Health Workers Center" },
  { id: "PRIV_PRACT,N,12,0", label: "Private Practitioners" },
  { id: "SUBS_PRACT,N,13,0", label: "Subsidized Practitioners" },
  { id: "OTHER_MI,N,10,0", label: "Other Medical Institution" },
  { id: "PT_AVALAIB,C,12", label: "Postal Telegraph Availability" },
  { id: "PR_DISTANC,N,12,0", label: "Distance to Postal Telegraph" },
  { id: "POST_OFFIC,N,12,0", label: "Post Office" },
  { id: "TELEG_OFFI,N,12,0", label: "Telegraph Office" },
  { id: "PT_OFFICE,N,11,0", label: "Postal Telegraph Office" },
  { id: "PHONE_CONN,N,14,0", label: "Phone Connection" },
  { id: "DW_AVALAIB,C,13", label: "Drinking Water Availability" },
  { id: "DW_DISTANC,N,13,0", label: "Distance to Drinking Water Source" },
  { id: "DW_TAP,N,8,0", label: "Drinking Water Tap" },
  { id: "DW_WELL,N,10,0", label: "Drinking Water Well" },
  { id: "DW_TUBEWEL,N,14,0", label: "Drinking Water Tube Well" },
  { id: "DW_HANDPUM,N,14,0", label: "Drinking Water Hand Pump" },
  { id: "DW_RIVER,N,10,0", label: "Drinking Water River" },
  { id: "DW_FOUNTAI,N,13,0", label: "Drinking Water Fountain" },
  { id: "DW_SPRING,N,12,0", label: "Drinking Water Spring" },
  { id: "DW_CANAL,N,11,0", label: "Drinking Water Canal" },
  { id: "DW_TANK,N,10,0", label: "Drinking Water Tank" },
  { id: "DW_OTHER,N,11,0", label: "Other Drinking Water Source" },
  { id: "MK_AVALAIB,C,12", label: "Market Availability" },
  { id: "MK_DISTANC,N,12,0", label: "Distance to Market" },
  { id: "DAILY_MK,N,10,0", label: "Daily Market" },
  { id: "CF_AVALAIB,C,12", label: "Community Facility Availability" },
  { id: "CF_DISTANC,N,12,0", label: "Distance to Community Facility" },
  { id: "BUS_STOP,N,11,0", label: "Bus Stop" },
  { id: "RAILWAY,N,9,0", label: "Railway" },
  { id: "PUCCA_ROAD,N,13,0", label: "Pucca Road" },
  { id: "KACHCHA_RO,N,13,0", label: "Kachcha Road" },
  { id: "FOOTPATH,N,11,0", label: "Footpath" },
  { id: "NEAR_TOWN,C,16", label: "Nearest Town" },
  { id: "DIST_TOWN,N,11,0", label: "Distance to Town" },
  { id: "PW_AVALAIB,C,13", label: "Power Availability" },
  { id: "PW_DOMESTI,N,13,0", label: "Power for Domestic Use" },
  { id: "PW_AGRICUL,N,13,0", label: "Power for Agriculture" },
  { id: "PW_IND_COM,N,13,0", label: "Power for Industry and Commerce" },
  { id: "PW_FOR_ALL,N,13,0", label: "Power for All Purposes" },
  { id: "LU_FOREST,N,11,0", label: "Land Use Forest" },
  { id: "LU%_FOREST,N,13,2", label: "Percentage Land Use Forest" },
  { id: "LU_IRRIGAT,N,11,0", label: "Land Use Irrigated" },
  { id: "LU%_IRRIGA,N,12,2", label: "Percentage Land Use Irrigated" },
  { id: "LU_UNIRRIG,N,11,0", label: "Land Use Unirrigated" },
  { id: "LU%_UNIRRI,N,12,2", label: "Percentage Land Use Unirrigated" },
  { id: "LU_CULT_WA,N,13,0", label: "Land Use Cultivable Waste" },
  { id: "LU%_CULT_W,N,13,2", label: "Percentage Land Use Cultivable Waste" },
  { id: "LU_NON_CUL,N,13,0", label: "Land Use Non-Cultivable" },
  { id: "LU%_NON_C,N,12,2", label: "Percentage Land Use Non-Cultivable" },
  { id: "IR_WELL,N,9,2", label: "Irrigation by Well" },
  { id: "IR_TUBEWEL,N,12,2", label: "Irrigation by Tube Well" },
  { id: "IR_TANK,N,8,2", label: "Irrigation by Tank" },
  { id: "IR_LAKE,N,8,2", label: "Irrigation by Lake" },
  { id: "IR_RIVER,N,9,2", label: "Irrigation by River" },
  { id: "IR_GVT_CAN,N,12,2", label: "Irrigation by Government Canal" },
  { id: "IR_PRIV_CA,N,11,2", label: "Irrigation by Private Canal" },
  { id: "IR_OTHER,N,10,2", label: "Other Irrigation" },
];


const QueryComponent = ({ applyFilters, revertFeatures, year, selection, level, selectedDistrict, selectedSubdistrict }) => {
  const [fields, setFields] = useState([]);

  const getFieldsForYear = () => {
    if (year === "1991") {
      
        if (selection === "Total") return total_1991;
        if (selection === "Urban") return urban_1991;
        if (selection === "Rural" && level=== "District_Rural") return dt_rur_1991;
        if (selection === "Rural" && level === "Subdistrict") return taluk_1991;
     if (selection === "district") {
        if (selectedSubdistrict === "subdistrict") return taluk_1991;
        if (selectedSubdistrict === "village") return village_1991;
        if (selectedSubdistrict === "urban") return urban_1991;
      } else if (selection === "subdistrict") {
        return village_1991;
      }
    } else if (year === "2001") {
      return fields2001;
    } else if (year === "2011") {
      return fields2011;
    }
    return [];
  };

  const addField = () => {
    const select = document.getElementById("addField");
    const fieldId = select.value;
    if (fieldId) {
      const field = getFieldsForYear().find((f) => f.id === fieldId);
      if (field) {
        setFields([...fields, field]);
        select.value = ""; // Reset the select
      }
    }
  };

  const removeField = (fieldId) => {
    const updatedFields = fields.filter((field) => field.id !== fieldId);
    setFields(updatedFields);
    handleApplyFilters(updatedFields); // Apply filters again with updated fields
  };

  useEffect(() => {
    fields.forEach((field) => {
      const operatorSelect = document.getElementById(`${field.id}_op`);
      const secondInput = document.getElementById(`${field.id}_2`);

      const handleOperatorChange = () => {
        if (operatorSelect.value === "between") {
          secondInput.style.display = "inline-block";
        } else {
          secondInput.style.display = "none";
        }
      };

      operatorSelect.addEventListener("change", handleOperatorChange);

      // Initial check
      handleOperatorChange();
    });
  }, [fields]);

  const handleApplyFilters = (currentFields = []) => {
    const filters = {};
    (currentFields.length ? currentFields : fields).forEach((field) => {
      const operator = document.getElementById(`${field.id}_op`).value;
      const value = parseFloat(document.getElementById(field.id).value);
      const value2 = parseFloat(document.getElementById(`${field.id}_2`).value);
      filters[field.id] = { operator, value, value2 };
    });
    applyFilters(filters);
  };

  return (
    <div id="controls" className="query-controls">
      <label htmlFor="addField">Add Field: </label>
      <select id="addField" onChange={addField}>
        <option value="">Select Field</option>
        {getFieldsForYear().map((field) => (
          <option key={field.id} value={field.id}>
            {field.label}
          </option>
        ))}
      </select>
      <div id="filters">
        {fields.map((field) => (
          <div
            key={field.id}
            id={`${field.id}_controls`}
            className="filter-group"
          >
            <label htmlFor={field.id}>{field.label}: </label>
            <select id={`${field.id}_op`}>
              <option value="<">Less Than</option>
              <option value=">">Greater Than</option>
              <option value="=">Equal To</option>
              <option value="between">Between</option>
            </select>
            <input type="text" id={field.id} />
            <input
              type="text"
              id={`${field.id}_2`}
              style={{ display: "none" }}
            />
            <button
              onClick={() => removeField(field.id)}
              className="btn btn-danger btn-sm"
            >
              Remove
            </button>
          </div>
        ))}
      </div>
      <button
        onClick={() => handleApplyFilters()}
        className="btn btn-primary mt-3"
      >
        Apply Filter
      </button>
      <button onClick={revertFeatures} className="btn btn-secondary mt-3">
        Revert
      </button>
    </div>
  );
};

export default QueryComponent;